name: Cribl CI/CD
# Workflow to build and test Cribl QA Engineering Take Home Project
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # Setup dependencies.
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25.x'
      - run: npm ci

      # Start containers (target_1, target_2 & splitter) and run unit + integration tests.
      - name: Build/start containers and run all tests
        run: docker compose up --build --abort-on-container-exit
        continue-on-error: true

      - name: Generate Allure Report HTML
        # The allure command line is needed to generate the report
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure Report artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
          name: github-pages
          
  deploy-report:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # Link to the published report
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploys the 'github-pages' artifact
